name: Generate GitHub Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Smriti-Prajapati
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: output/github-contribution-grid-snake.svg

      - name: Commit & Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Update GitHub Snake"
          add: "output/github-contribution-grid-snake.svg"
